version: '3.8'
services:
nginx:
  image: nginx:1.23.3
  ports:
    - "80:80"
  volumes:
    - /home/root/test_servere/FE_MeBeReact/app-project-master/build:/usr/share/nginx/html
    - /home/root/test_servere/docker/nginx.conf:/etc/nginx/conf.d/default.conf
  depends_on:
    - backend
  networks:
    - mebenet
networks:
  mebenet:
    driver: bridge
